# Generated by Django 3.2 on 2021-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='realase_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
