# Generated by Django 3.2 on 2021-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk1', '0003_alter_film_realase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movielength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
