# Generated by Django 3.2 on 2021-04-25 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk1', '0006_auto_20210425_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appk1.film')),
            ],
        ),
    ]
