# Generated by Django 3.2 on 2021-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk1', '0008_auto_20210425_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('films', models.ManyToManyField(to='appk1.Film')),
            ],
        ),
    ]
